# Generated by Django 5.1.2 on 2024-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contacts_alter_services_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=250)),
            ],
        ),
    ]
